name: hakyll-images
version: '0.3.1'
github: "LaurentRDC/hakyll-images"
license: BSD3
author: "Laurent P. René de Cotret"
maintainer: "Laurent P. René de Cotret"
synopsis: "Hakyll utilities to work with images"
description: 
  hakyll-images is an add-on to the hakyll package. It adds utilities to work
  with images, including JPEG compression. 
category: Web
license-file: LICENSE.md

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

data-files:
- tests\data\*.jpg

ghc-options: -Wall -Wcompat

library:
  dependencies:
  - base              >= 4.8 && < 5
  - binary            >= 0.5 && < 0.10
  - bytestring        >= 0.9 && < 0.11
  - hakyll            > 4
  - JuicyPixels       >= 3
  - JuicyPixels-extra > 0.3
  source-dirs: library
  exposed-modules:
  - Hakyll.Images
  - Hakyll.Images.CompressJpg
  - Hakyll.Images.Resize

tests:
  spec:
    source-dirs: 
      - tests
      - library
    main: TestSuite.hs
    dependencies:
    - hakyll-images
    - tasty             >= 0.11 && < 1.2
    - tasty-hunit       >= 0.9  && < 0.11
    - HUnit-approx      >= 1.0.0.0
    - filepath          >= 1.0  && < 1.5
    - directory         >= 1.0
    # Base hakyll-images dependencies
    - base              >= 4.8 && < 5
    - binary            >= 0.5 && < 0.10
    - bytestring        >= 0.9 && < 0.11
    - hakyll            > 4
    - JuicyPixels       >= 3
    - JuicyPixels-extra > 0.3
