name: hakyll-images
version: '0.0.1'
github: "LaurentRDC/hakyll-images"
license: BSD3
author: "Laurent P. René de Cotret"
maintainer: "Laurent P. René de Cotret"
synopsis: "Hakyll utilities to work with images, including JPEG compression and image re-sizing."
# description: hakyll-images is a new Haskeleton package.
category: Web

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

data-files:
- tests\data\*.jpg

ghc-options: -Wall -Wcompat

library:
  dependencies:
  - base              >= 4.8 && < 5
  - bytestring        >= 0.9 && < 0.11
  - filepath          >= 1.0 && < 1.5
  - hakyll            > 4
  - JuicyPixels       > 3 && < 4
  - JuicyPixels-extra > 0.3
  source-dirs: library
  exposed-modules:
  - Hakyll.Images.CompressJpg

tests:
  spec:
    source-dirs: 
      - tests
      - library
    main: TestSuite.hs
    dependencies:
    - hakyll-images
    - tasty             >= 0.11 && < 1.2
    - tasty-hunit       >= 0.9  && < 0.11
    # Base hakyll-images dependencies
    - base              >= 4.8 && < 5
    - bytestring        >= 0.9 && < 0.11
    - filepath          >= 1.0 && < 1.5
    - hakyll            > 4
    - JuicyPixels       > 3 && < 4
    - JuicyPixels-extra > 0.3
