name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-test:
    if: contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    # Stack 2.7.1 is not able to install ghc 9.0.1 alongside chocolatey's GHC
    - name: Remove hosted GHC9
      if: runner.os == 'Windows'
      run:
        choco uninstall ghc --yes

    - uses: actions/cache@v2
      name: Cache Haskell build artifacts
      with:
        path: ~/.stack
        key: ${{ runner.os }}-v2-${{ hashFiles('stack.*') }}

    - name: Build 
      run: stack test --no-run-tests --ghc-options=-Werror
    
    - name: Unit tests
      run: stack test 

  release:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Create release description
      run: |
        python release-description.py CHANGELOG.md > description.md
        cat description.md

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body_path: description.md
